spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
#          uri: https://github.com/how2j/springcloudConfig/
          uri: https://github.com/295954776/springcloudConfig/
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/